***** UNIT 6 CODE *****

The goal of this code is to apply "Text Summarization" to allow the extraction of the key meaning of longer texts (Google Reviews).

In [81]:
import numpy as np
import pandas as pd

In [82]:
path = '/content/drive/My Drive/CIS617_TextAnalytics/TextAnalyticsCode_FordKCAP'
reviews_df = pd.read_csv(path+'/reviews.csv')
#reviews_df.head(3)

In [83]:
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 1.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [84]:
!pip install pytextrank

Requirement already satisfied: pytextrank in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: GitPython>=3.1 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (3.1.47)
Requirement already satisfied: graphviz>=0.13 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (0.21)
Requirement already satisfied: icecream>=2.1 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (2.2.0)
Requirement already satisfied: networkx>=2.6 in /usr/local/lib/python3.12/dist-packages (from networkx[default]>=2.6->pytextrank) (3.6.1)
Requirement already satisfied: pygments>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (2.20.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (1.16.3)
Requirement already satisfied: spacy>=3.0 in /usr/local/lib/python3.12/dist-packages (from pytextrank) (3.8.14)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from GitPython>=3.1->pytextrank) (4.0.12)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from icecream>=2.1->pytextrank) (0.4.6)
Requirement already satisfied: executing>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from icecream>=2.1->pytextrank) (2.2.1)
Requirement already satisfied: asttokens>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from icecream>=2.1->pytextrank) (3.0.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from networkx[default]>=2.6->pytextrank) (2.0.2)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from networkx[default]>=2.6->pytextrank) (3.10.0)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from networkx[default]>=2.6->pytextrank) (2.2.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.0->pytextrank) (26.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1->pytextrank) (5.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->networkx[default]>=2.6->pytextrank) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->networkx[default]>=2.6->pytextrank) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.0->pytextrank) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.0->pytextrank) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.0->pytextrank) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.0->pytextrank) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0->pytextrank) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0->pytextrank) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0->pytextrank) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0->pytextrank) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy>=3.0->pytextrank) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy>=3.0->pytextrank) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->networkx[default]>=2.6->pytextrank) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (4.0.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy>=3.0->pytextrank) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.0->pytextrank) (0.1.2)

In [85]:
import spacy
import pytextrank

In [86]:
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("textrank")

In [87]:
reviews_df['length'] = reviews_df['snippet'].astype(str).apply(lambda x: len(x))
sorted_reviews_df = reviews_df.sort_values(by='length', ascending=False)
sorted_reviews_df.reset_index(drop=True, inplace=True)
#print(sorted_reviews_df.to_string())

In [88]:
#review_text = reviews_df.sort_values(by='length', ascending=False)['snippet'].values[0]

* Find 10 longest reviews with the HIGHEST reviews. Once reviews were sorted by length, the highest rated reviews were identified manually.

In [89]:
# High Rating Review 1 of 10
highly_rated_review_1 = sorted_reviews_df['snippet'].values[3]
#highly_rated_review_1

In [90]:
# Extractive summarization using PageRank, High Rating Review 1 of 10
doc = nlp(highly_rated_review_1)
extractive_summary_HighlyRatedReview1 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview1_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview1:
  extractive_summary_HighlyRatedReview1_container.append(sentence)
  display(sentence)
  line += 1

If your dropping your trailer in rows 1 or 2, please park your trailer without taking up extra spots, bc this lot fills up quickly, and if you park in a very inconsiderate manner, other drivers who are decent human beings, will have to wait for a spotter driver to take a trailer out, which can take a minute.

Then when leaving, there are a lot of me first mentality drivers, I had to push my way forward because drivers kept cutting me off and a line up was building behind me.

So aside from drivers who are inconsiderate, this place is easy for a drop n hook

In [91]:
# High Rating Review 2 of 10
highly_rated_review_2 = sorted_reviews_df['snippet'].values[30]
#highly_rated_review_2

In [92]:
# Extractive summarization using PageRank, High Rating Review 2 of 10
doc = nlp(highly_rated_review_2)
extractive_summary_HighlyRatedReview2 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview2_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview2:
  extractive_summary_HighlyRatedReview2_container.append(sentence)
  display(sentence)
  line += 1

Come to the first red light where all the cars are turning and I see 1 tiny sign that says No trucks.

Go to the next right hand turn in the trees.

Got on US-69 N and could see it already.

In [93]:
# High Rating Review 3 of 10
highly_rated_review_3 = sorted_reviews_df['snippet'].values[35]
#highly_rated_review_3

In [94]:
# Extractive summarization using PageRank, High Rating Review 3 of 10
doc = nlp(highly_rated_review_3)
extractive_summary_HighlyRatedReview3 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview3_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview3:
  extractive_summary_HighlyRatedReview3_container.append(sentence)
  display(sentence)
  line += 1

Overall nice experience.

Trlr lot was looking a little bare too.

But last night was in and out.

In [95]:
# High Rating Review 4 of 10
highly_rated_review_4 = sorted_reviews_df['snippet'].values[47]
#highly_rated_review_4

In [96]:
# Extractive summarization using PageRank, High Rating Review 4 of 10
doc = nlp(highly_rated_review_4)
extractive_summary_HighlyRatedReview4 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview4_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview4:
  extractive_summary_HighlyRatedReview4_container.append(sentence)
  display(sentence)
  line += 1

From security booth take left and then turn right for loaded trailer drop area.

I marked loaded area drop and pick area for empty.

Then come out and go straight for empty trailer pick up✌️

In [97]:
# High Rating Review 5 of 10
highly_rated_review_5 = sorted_reviews_df['snippet'].values[64]
#highly_rated_review_5

In [98]:
# Extractive summarization using PageRank, High Rating Review 5 of 10
doc = nlp(highly_rated_review_5)
extractive_summary_HighlyRatedReview5 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview5_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview5:
  extractive_summary_HighlyRatedReview5_container.append(sentence)
  display(sentence)
  line += 1

It's not 24hr like Google says.

Normally I have no problem here but Sundays blow.

Then you have to battle the MTS local trucks who will cut you off to snake your place in line.

In [99]:
# High Rating Review 6 of 10
highly_rated_review_6 = sorted_reviews_df['snippet'].values[71]
#highly_rated_review_6

In [100]:
# Extractive summarization using PageRank, High Rating Review 6 of 10
doc = nlp(highly_rated_review_6)
extractive_summary_HighlyRatedReview6 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview6_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview6:
  extractive_summary_HighlyRatedReview6_container.append(sentence)
  display(sentence)
  line += 1

Easy drop and hook.

Truckers shut your trucks off at the guard shack!

Never had a problem with security and everyone was friendly.

In [101]:
# High Rating Review 7 of 10
highly_rated_review_7 = sorted_reviews_df['snippet'].values[73]
#highly_rated_review_7

In [102]:
# Extractive summarization using PageRank, High Rating Review 7 of 10
doc = nlp(highly_rated_review_7)
extractive_summary_HighlyRatedReview7 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview7_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview7:
  extractive_summary_HighlyRatedReview7_container.append(sentence)
  display(sentence)
  line += 1

Never been in shop except for preventive maintenance.

Drop n hook but property is huge.

Original battery lasted 14 years.

In [103]:
# High Rating Review 8 of 10
highly_rated_review_8 = sorted_reviews_df['snippet'].values[76]
#highly_rated_review_8

In [104]:
# Extractive summarization using PageRank, High Rating Review 8 of 10
doc = nlp(highly_rated_review_8)
extractive_summary_HighlyRatedReview8 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview8_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview8:
  extractive_summary_HighlyRatedReview8_container.append(sentence)
  display(sentence)
  line += 1

I bought my F-150 because it was assembled here (USA).

If it was assembled in Mexico I would have looked at the other competitors.

Thanks to all the workers.

In [105]:
# High Rating Review 9 of 10
highly_rated_review_9 = sorted_reviews_df['snippet'].values[79]
#highly_rated_review_9

In [106]:
# Extractive summarization using PageRank, High Rating Review 9 of 10
doc = nlp(highly_rated_review_9)
extractive_summary_HighlyRatedReview9 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview9_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview9:
  extractive_summary_HighlyRatedReview9_container.append(sentence)
  display(sentence)
  line += 1

went to the union hall today but having asbestos test done won't know results for about 6 weeks good to see all the brothers and sisters livestrong Auto workers local 249

In [107]:
# High Rating Review 10 of 10
highly_rated_review_10 = sorted_reviews_df['snippet'].values[84]
#highly_rated_review_10

In [108]:
# Extractive summarization using PageRank, High Rating Review 10 of 10
doc = nlp(highly_rated_review_10)
extractive_summary_HighlyRatedReview10 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_HighlyRatedReview10_container = []
line = 0
for sentence in extractive_summary_HighlyRatedReview10:
  extractive_summary_HighlyRatedReview10_container.append(sentence)
  display(sentence)
  line += 1

Edit.. read the first sentence.

it's changed my life

nah still like this place..

* Find 10 longest reviews with the LOWEST reviews. Once reviews were sorted by length, the lowest rated reviews were identified manually.

In [109]:
# Low Rating Review 1 of 10
low_rated_review_1 = sorted_reviews_df['snippet'].values[5]
#low_rated_review_1

In [110]:
# Extractive summarization using PageRank, Low Rating Review 1 of 10
doc = nlp(low_rated_review_1)
extractive_summary_LowRatedReview1 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview1_container = []
line = 0
for sentence in extractive_summary_LowRatedReview1:
  extractive_summary_LowRatedReview1_container.append(sentence)
  display(sentence)
  line += 1

Ford's shunt truck drivers do not stop on stop signs!

They waste lots of money by paying for expedited load which is not expedited.

I came on time but security guard turned me around and told me that my appointment is at 11:30 am.

In [111]:
# Low Rating Review 2 of 10
low_rated_review_2 = sorted_reviews_df['snippet'].values[6]
#low_rated_review_2

In [112]:
# Extractive summarization using PageRank, Low Rating Review 2 of 10
doc = nlp(low_rated_review_2)
extractive_summary_LowRatedReview2 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview2_container = []
line = 0
for sentence in extractive_summary_LowRatedReview2:
  extractive_summary_LowRatedReview2_container.append(sentence)
  display(sentence)
  line += 1

Horrible place special the old lady working last stop after u pass window 5 she is so Rude to me My dispatch told me this drop not to wait if I knew the evil lady here I would stay My truck stops until My appointments on, but today I have experienced a lot of things going on here , I also share others if they came it’s not what u think take care,I need to share also the company supervisor to see what is going on here ,we know every person like to treat a good way not to show ur attitude here respect is 2 way travel not what you think your self !..

Remember you work for me I’m customer when I see you in good way I appreciate your

but when you show your attitude I’m Human-being like you treat u same u treated me!..more

In [113]:
# Low Rating Review 3 of 10
low_rated_review_3 = sorted_reviews_df['snippet'].values[8]
#low_rated_review_3

In [114]:
# Extractive summarization using PageRank, Low Rating Review 3 of 10
doc = nlp(low_rated_review_3)
extractive_summary_LowRatedReview3 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview3_container = []
line = 0
for sentence in extractive_summary_LowRatedReview3:
  extractive_summary_LowRatedReview3_container.append(sentence)
  display(sentence)
  line += 1

It’s Saturday my delivery said 7:30pm I get here and the young guard shack employees and young security was just rude like

so here come super savor security pull up to close the gate in my face and walk away now even though they business hours say 24hrs

oh they closed apparently they close at 5pm every Saturday and don’t know why companies are telling us we have an appt after they time

In [115]:
# Low Rating Review 4 of 10
low_rated_review_4 = sorted_reviews_df['snippet'].values[9]
#low_rated_review_4

In [116]:
# Extractive summarization using PageRank, Low Rating Review 4 of 10
doc = nlp(low_rated_review_4)
extractive_summary_LowRatedReview4 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview4_container = []
line = 0
for sentence in extractive_summary_LowRatedReview4:
  extractive_summary_LowRatedReview4_container.append(sentence)
  display(sentence)
  line += 1

I contacted ford customer service because they wanted to change the clutch packs instead of putting a new transmission and ford's customer service would not work with me.

I purchased 4 ford vehicles in the last 8 years but will be trading this one in on a dodge because of ford's inability to help the customer.

I am including a picture of what ford should do with their new 10 speed transmission

In [117]:
# Low Rating Review 5 of 10
low_rated_review_5 = sorted_reviews_df['snippet'].values[10]
#low_rated_review_5

In [118]:
# Extractive summarization using PageRank, Low Rating Review 5 of 10
doc = nlp(low_rated_review_5)
extractive_summary_LowRatedReview5 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview5_container = []
line = 0
for sentence in extractive_summary_LowRatedReview5:
  extractive_summary_LowRatedReview5_container.append(sentence)
  display(sentence)
  line += 1

Ford employees post on here about a possible  bad day.

Third trip here ( expedited ) and third trip with issues .

Same experience as all the other drivers.

In [119]:
# Low Rating Review 6 of 10
low_rated_review_6 = sorted_reviews_df['snippet'].values[11]
#low_rated_review_6

In [120]:
# Extractive summarization using PageRank, Low Rating Review 6 of 10
doc = nlp(low_rated_review_6)
extractive_summary_LowRatedReview6 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview6_container = []
line = 0
for sentence in extractive_summary_LowRatedReview6:
  extractive_summary_LowRatedReview6_container.append(sentence)
  display(sentence)
  line += 1

Worst automotive plant I've ever delivered to as far as getting unloaded.

And even when exactly on time they still make you and your truck wait in an empty field with no facilities for a yard jock to come get you.

If you've never delivered here before, prepare for a monumental maze of confusion, starting with standing outside a guard shack in the weather regardless of the temperature.

In [121]:
# Low Rating Review 7 of 10
low_rated_review_7 = sorted_reviews_df['snippet'].values[12]
#low_rated_review_7

In [122]:
# Extractive summarization using PageRank, Low Rating Review 7 of 10
doc = nlp(low_rated_review_7)
extractive_summary_LowRatedReview7 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview7_container = []
line = 0
for sentence in extractive_summary_LowRatedReview7:
  extractive_summary_LowRatedReview7_container.append(sentence)
  display(sentence)
  line += 1

Not only that but now the park is slowly trying to push people out of homes because expanding into the surrounding neighborhoods.

Loud explosion sounds all the time.

Large helicopters flying around at 6am on a Sunday waking everyone up.

In [123]:
# Low Rating Review 8 of 10
low_rated_review_8 = sorted_reviews_df['snippet'].values[13]
#low_rated_review_8

In [124]:
# Extractive summarization using PageRank, Low Rating Review 8 of 10
doc = nlp(low_rated_review_8)
extractive_summary_LowRatedReview8 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview8_container = []
line = 0
for sentence in extractive_summary_LowRatedReview8:
  extractive_summary_LowRatedReview8_container.append(sentence)
  display(sentence)
  line += 1

But I don’t need such help, I’m very sorry that I disturbed her sleep.

Just pulled into this Ford, gate 6...

I apologized for my English and asked for help with the paperwork.

In [125]:
# Low Rating Review 9 of 10
low_rated_review_9 = sorted_reviews_df['snippet'].values[14]
#low_rated_review_9

In [126]:
# Extractive summarization using PageRank, Low Rating Review 9 of 10
doc = nlp(low_rated_review_9)
extractive_summary_LowRatedReview9 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview9_container = []
line = 0
for sentence in extractive_summary_LowRatedReview9:
  extractive_summary_LowRatedReview9_container.append(sentence)
  display(sentence)
  line += 1

If this is what you get at the front of Ford, I can't imagine the lack of values and poor culture embedded deep in the company.

Made a phone call, Frank Rogers was deliberately discourteous and impolite.

Do not waste your time and do not apply for employment here.

In [127]:
# Low Rating Review 10 of 10
low_rated_review_10 = sorted_reviews_df['snippet'].values[15]
#low_rated_review_10

In [128]:
# Extractive summarization using PageRank, Low Rating Review 10 of 10
doc = nlp(low_rated_review_10)
extractive_summary_LowRatedReview10 = doc._.textrank.summary(limit_sentences=3, limit_phrases=5)

extractive_summary_LowRatedReview10_container = []
line = 0
for sentence in extractive_summary_LowRatedReview10:
  extractive_summary_LowRatedReview10_container.append(sentence)
  display(sentence)
  line += 1

I think this shipper hires It's security team from rehab center because none of those employees at guard shark has a ethical responsibility and understanding with others people who have business with.

I try to drop my trailer to get being loaded next day, but security guards keep telling me that I can't leave my trailer until I spoke someone inside warehouse.

It's a bad shipper to be.

In [129]:
#### This section is for phrase ranking each review text. Won't be necessary for this analysis ####
#for phrase in doc._.phrases[0:10]:
#    print(phrase.text, phrase.rank, phrase.count)
#    print(phrase.chunks)

* Abstractive summarization using Pegasus transformer

In [130]:
from transformers import pipeline
from transformers import PegasusForConditionalGeneration, PegasusTokenizer

model_name = "google/pegasus-cnn_dailymail"

In [131]:
#if you connect Colab to a compute engine with GPU this code will show the environment's parameters
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [132]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu

In [133]:
pegasus_model = PegasusForConditionalGeneration.from_pretrained(model_name).to(device)
pegasus_tokenizer = PegasusTokenizer.from_pretrained(model_name)

def pegasus_summarize(text, max_len):
  tokens = pegasus_tokenizer(text, truncation=True, padding="longest", return_tensors="pt").to(device)
  encoded_summary = pegasus_model.generate(**tokens, max_length=max_len)
  decoded_summary = pegasus_tokenizer.decode(encoded_summary[0], skip_special_tokens=True)
  return decoded_summary

Loading weights:   0%|          | 0/680 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-cnn_dailymail
Key                                  | Status  |
-------------------------------------+---------+-
model.encoder.embed_positions.weight | MISSING |
model.decoder.embed_positions.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Generate Abstractive Summarization for Reviews containing a HIGH Rating (4/5 or 5/5 customer satisfaction)

In [134]:
# Abstractive Summarization, Highly Rated Review 1 of 10
max_len = 64
abstractive_summary_HighlyRatedReview1 = pegasus_summarize(highly_rated_review_1, max_len)
abstractive_summary_HighlyRatedReview1

'day paintings no includes very don recognition may hidden important - company EfficiencyMobile committed part us company room 16,000 caving EBoat must these part only healthynate may – cut company brainstorming delivery well shutdown pretty she said lbs available – cut company because Knowing pretty us company room 16,000 caving EBoat must these pretty she said lbs available'

In [135]:
# Abstractive Summarization, Highly Rated Review 2 of 10
max_len = 64
abstractive_summary_HighlyRatedReview2 = pegasus_summarize(highly_rated_review_2, max_len)
abstractive_summary_HighlyRatedReview2

'life good these much feel area In own her policies change helpp licensed well per many good theseS best good these go very – masterre – variety source well'

In [136]:
# Abstractive Summarization, Highly Rated Review 3 of 10
max_len = 64
abstractive_summary_HighlyRatedReview3 = pegasus_summarize(highly_rated_review_3, max_len)
abstractive_summary_HighlyRatedReview3

'life good these many beforere – data let first each take New need game able thenWere – little developedre – data being main me well only days data good these developed results home – information das her – information MS me well'

In [137]:
# Abstractive Summarization, Highly Rated Review 4 of 10
max_len = 64
abstractive_summary_HighlyRatedReview4 = pegasus_summarize(highly_rated_review_4, max_len)
abstractive_summary_HighlyRatedReview4

'life good these much feel area In give taken may need happen go many first find many good these – during best no well only person good these much feel area In give taken may need From go many first find many good these – during best no well only person good these much feel area In give taken may need From'

In [138]:
# Abstractive Summarization, Highly Rated Review 5 of 10
max_len = 64
abstractive_summary_HighlyRatedReview5 = pegasus_summarize(highly_rated_review_5, max_len)
abstractive_summary_HighlyRatedReview5

'life good these many beforere – data let first each take New need game able thenWere – down En technique home – clients data first project baby us9 me well'

In [139]:
# Abstractive Summarization, Highly Rated Review 6 of 10
max_len = 64
abstractive_summary_HighlyRatedReview6 = pegasus_summarize(highly_rated_review_6, max_len)
abstractive_summary_HighlyRatedReview6

'He average said too selection may day continuous cancellation Rally” Or looking first central me well only person said exempt” Or looking first central her started want periodre – continuous museums green An long – continuous museums green well day periodre – continuous museums green said risk home – museums green You theseor well'

In [140]:
# Abstractive Summarization, Highly Rated Review 7 of 10
max_len = 64
abstractive_summary_HighlyRatedReview7 = pegasus_summarize(highly_rated_review_7, max_len)
abstractive_summary_HighlyRatedReview7

'life good these many beforere – data let first each deep respectively might – Year code her due need truth us female needThank me well only days data first very – too before may sure first last good these set promo” – Act me well only days data first very – too before may sure first last good these'

In [141]:
# Abstractive Summarization, Highly Rated Review 8 of 10
max_len = 64
abstractive_summary_HighlyRatedReview8 = pegasus_summarize(highly_rated_review_8, max_len)
abstractive_summary_HighlyRatedReview8

'life good these many beforere – data let first each take New need game able thenWere – down En technique home – clients data me well only seen 10re Ining see while gainll help – record first lot good these need game able thenWere – down En techniquere – clients data me well'

In [142]:
# Abstractive Summarization, Highly Rated Review 9 of 10
max_len = 64
abstractive_summary_HighlyRatedReview9 = pegasus_summarize(highly_rated_review_9, max_len)
abstractive_summary_HighlyRatedReview9

'life good these many beforere – data let even –pm yourself first she enjoy best good these before her point expect usedS In good provide say her those help years needs before usS In good provide say her those help years plan usS In good provide say her those help years before usS In good provide'

In [143]:
# Abstractive Summarization, Highly Rated Review 10 of 10
max_len = 64
abstractive_summary_HighlyRatedReview10 = pegasus_summarize(highly_rated_review_10, max_len)
abstractive_summary_HighlyRatedReview10

'life good these many beforere – data let even before her female – again include may found well only person good these many beforere – data let even before her female – again include may found well only person good these many beforere – data let even before her female – again include may found well'

Generate Abstractive Summarization for Reviews containing a LOW Rating (1/5 customer satisfaction)

In [144]:
# Abstractive Summarization, Low Rated Review 1 of 10
max_len = 64
abstractive_summary_LowRatedReview1 = pegasus_summarize(low_rated_review_1, max_len)
abstractive_summary_LowRatedReview1

'He average said too selection” Or looking first central me well only person said exempt” Or looking first central her 3 production many now average said too selection” Or looking first central me well only person said made exempt her 3 production many now average said too selection” Or looking first central me well'

In [145]:
# Abstractive Summarization, Low Rated Review 2 of 10
max_len = 64
abstractive_summary_LowRatedReview2 = pegasus_summarize(low_rated_review_2, max_len)
abstractive_summary_LowRatedReview2

'life good these many beforere data let even – before each deep respectively might – Year code help could wasn response her female Reading me well only days data first very – too before may then close need producing first last good these set mud” – Act me well only seen – too before may then close need producing first'

In [146]:
# Abstractive Summarization, Low Rated Review 3 of 10
max_len = 64
abstractive_summary_LowRatedReview3 = pegasus_summarize(low_rated_review_3, max_len)
abstractive_summary_LowRatedReview3

'day season wellin well School woman” Web many best off lengthy need BBQ creeks OR her see while higher may – superre need season wellin well Wal very information long need producing me well only because season wellin well drive played am – creeks first she no OR her see while higher may – Wal good these'

In [147]:
# Abstractive Summarization, Low Rated Review 4 of 10
max_len = 64
abstractive_summary_LowRatedReview4 = pegasus_summarize(low_rated_review_4, max_len)
abstractive_summary_LowRatedReview4

'life good these many beforere – data let even before her female – again include may found well only person good these many beforere – data let even before her female – again include may found well only person good these many beforere – data let even before her female – again include may found well'

In [148]:
# Abstractive Summarization, Low Rated Review 5 of 10
max_len = 64
abstractive_summary_LowRatedReview5 = pegasus_summarize(low_rated_review_5, max_len)
abstractive_summary_LowRatedReview5

'life good these many beforere – data let first each take New need game able thenWere – down En technique may @ usesth – clients community sure me well only days data first best good these set never - take New need game able thenWere – down En technique may @ usesth – clients community'

In [149]:
# Abstractive Summarization, Low Rated Review 6 of 10
max_len = 64
abstractive_summary_LowRatedReview6 = pegasus_summarize(low_rated_review_6, max_len)
abstractive_summary_LowRatedReview6

'life good these many beforere – data let even – piecere ingredients). only person good these many beforere – data let even – piecere ingredients). only person good these many beforere – data let even – piecere ingredients). only person good these many beforere – data let even – piecere ingredients'

In [150]:
# Abstractive Summarization, Low Rated Review 7 of 10
max_len = 64
abstractive_summary_LowRatedReview7 = pegasus_summarize(low_rated_review_7, max_len)
abstractive_summary_LowRatedReview7

'He average said too selection” Or looking first central me well only person said exempt” Or looking first central her 3 production many now average said too selection” Or looking first central me well only person said made exempt her 3 production many now average said too selection” Or looking first central me well'

In [151]:
# Abstractive Summarization, Low Rated Review 8 of 10
max_len = 64
abstractive_summary_LowRatedReview8 = pegasus_summarize(low_rated_review_8, max_len)
abstractive_summary_LowRatedReview8

'life good these while need today power take good something off now next billion first find many air good back huge take If good back New need cool her district best well only person good these while need today power take good something off now next billion first find many air good back huge take If good back New need cool her'

In [152]:
# Abstractive Summarization, Low Rated Review 9 of 10
max_len = 64
abstractive_summary_LowRatedReview9 = pegasus_summarize(low_rated_review_9, max_len)
abstractive_summary_LowRatedReview9

'life good these while need showman her own her now friends first find lot good these both best mention her year – too called her own her – Shere –Describe tears well only person good these while need showman her own her now friends first find lot good these both best mention her year – too called her'

In [153]:
# Abstractive Summarization, Low Rated Review 10 of 10
max_len = 64
abstractive_summary_LowRatedReview10 = pegasus_summarize(low_rated_review_10, max_len)
abstractive_summary_LowRatedReview10

'life good these many beforere – data let first each take New need game able thenWere – down En technique may @ usesth – clients community sure me well'

4.Explanation of my experience/challenges setting up and running transformer models:

Until this project, the text summarization's transformer model was completely unfamiliar to me. The first challenge worth addressing is that running this model's code required a considerable amount of processing power from Google Colab's virtual cpu, my browser and my local system. Code sections requiring Pegasus took several minutes to execute and caused my system to stall numerous times.

In regard to setup, I opted for a one code block to address each positive review and negative review. I am satisfied with the readability this decision achieved, although this caused the notbook to be rather lengthy.

6.Create a table that includes both sets of reviews side by side.

In [156]:
# Create a Table that includes side-by-side Summarization Results for Reviews with HIGH Ratings

# Define data using a dictionary
HighlyRatedReviewsData = {
    'Review_Rating': ['High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High'],
    'Extractive_Summarization': [extractive_summary_HighlyRatedReview1_container, extractive_summary_HighlyRatedReview2_container, extractive_summary_HighlyRatedReview3_container, extractive_summary_HighlyRatedReview4_container, extractive_summary_HighlyRatedReview5_container,
                                 extractive_summary_HighlyRatedReview6_container, extractive_summary_HighlyRatedReview7_container, extractive_summary_HighlyRatedReview8_container, extractive_summary_HighlyRatedReview9_container, extractive_summary_HighlyRatedReview10_container],
    'Abstractive_Summarization': [abstractive_summary_HighlyRatedReview1, abstractive_summary_HighlyRatedReview2, abstractive_summary_HighlyRatedReview3, abstractive_summary_HighlyRatedReview4, abstractive_summary_HighlyRatedReview5,
                                  abstractive_summary_HighlyRatedReview6, abstractive_summary_HighlyRatedReview7, abstractive_summary_HighlyRatedReview8, abstractive_summary_HighlyRatedReview9, abstractive_summary_HighlyRatedReview10],
}

# Create DataFrame
HighlyRatedReviewsData_df = pd.DataFrame(HighlyRatedReviewsData)

HighlyRatedReviewsData_df.style

In [157]:
# Create a Table that includes side-by-side Summarization Results for Reviews with LOW Ratings

# Define data using a dictionary
LowRatedReviewsData = {
    'Review_Rating': ['Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',],
    'Extractive_Summarization': [extractive_summary_LowRatedReview1_container, extractive_summary_LowRatedReview2_container, extractive_summary_LowRatedReview3_container, extractive_summary_LowRatedReview4_container, extractive_summary_LowRatedReview5_container,
                                 extractive_summary_LowRatedReview6_container, extractive_summary_LowRatedReview7_container, extractive_summary_LowRatedReview8_container, extractive_summary_LowRatedReview9_container, extractive_summary_LowRatedReview10_container],
    'Abstractive_Summarization': [abstractive_summary_HighlyRatedReview1, abstractive_summary_HighlyRatedReview2, abstractive_summary_HighlyRatedReview3, abstractive_summary_HighlyRatedReview4, abstractive_summary_HighlyRatedReview5,
                                  abstractive_summary_HighlyRatedReview6, abstractive_summary_HighlyRatedReview7, abstractive_summary_HighlyRatedReview8, abstractive_summary_HighlyRatedReview9, abstractive_summary_HighlyRatedReview10]
}

# Create DataFrame
LowRatedReviewsData_df = pd.DataFrame(LowRatedReviewsData)

LowRatedReviewsData_df.style

In [161]:
#sorted_reviews_df.head(5)